batch_size: 20
dataset_name: assgraphs_colony0123_framediffall
dataset_split:
- 0.8
- 0.2
- 0
dropout: 0.1
edge_dim: 6
encoder_num_layers: 5
hidden_channels: 120
lr: 0.0001
lr_decay: 0.9772372209558107
node_dim: 6
num_classes: 2
num_epochs: 90
num_layers: 11
seed: 0
